dist: trusty

language: node_js

node_js:
  - stable

before_script:
  - npm install

script:
  - ng build --prod --base-href /epic-video-comparator-demo/ && npm t

deploy:
  provider: pages
  skip_ cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: dev
